# ~ Forge.py | by ANXETY ~
# Refactored by SuperAssistant for standard Python execution

from Manager import m_download   # Every Download
import json_utils as js          # JSON

from pathlib import Path
import subprocess
import asyncio
import os
import sys # Ensure sys is imported

osENV = os.environ
CD = os.chdir

# Constants
UI = 'Forge'

# (auto-convert env vars to Path)
PATHS = {k: Path(v) for k, v in osENV.items() if k.endswith('_path')}   # k -> key; v -> value

HOME = PATHS['home_path']
VENV = PATHS['venv_path']
SCR_PATH = PATHS['scr_path']
SETTINGS_PATH = PATHS['settings_path']

WEBUI = HOME / UI
ENV_NAME = js.read(SETTINGS_PATH, 'ENVIRONMENT.env_name')

REPO_URL = f"https://huggingface.co/NagisaNao/ANXETY/resolve/main/{UI}.zip" # This might need to be a git repo for Forge
FORK_REPO = js.read(SETTINGS_PATH, 'ENVIRONMENT.fork')
BRANCH = js.read(SETTINGS_PATH, 'ENVIRONMENT.branch')
# Forge typically manages extensions within its own structure, EXTS might refer to a shared location or Forge's extension dir
EXTS_DIR_SETTING = js.read(SETTINGS_PATH, 'WEBUI.extension_dir') # From original, might be generic
FORGE_EXTENSIONS_PATH = WEBUI / 'extensions' # Standard Forge extension path

CD(HOME) # Initial CWD


# ==================== WEBUI OPERATIONS ====================

async def _download_file(url, directory, filename):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    file_path = directory / filename

    if file_path.exists():
        try:
            file_path.unlink()
        except OSError as e:
            print(f"Warning: Could not delete existing file {file_path}. Error: {e}", file=sys.stderr)

    process = await asyncio.create_subprocess_shell(
        f"curl -sLo \"{file_path}\" \"{url}\"", # Added quotes
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE
    )
    stdout, stderr = await process.communicate()
    if process.returncode != 0:
        print(f"Error downloading {url} to {file_path}. curl stderr: {stderr.decode() if stderr else 'No stderr'}", file=sys.stderr)

async def download_files(file_list):
    tasks = []
    for file_info in file_list:
        parts = file_info.split(',')
        url = parts[0].strip()
        directory_str = parts[1].strip() if len(parts) > 1 else str(WEBUI)
        filename = parts[2].strip() if len(parts) > 2 else Path(url).name
        tasks.append(_download_file(url, Path(directory_str), filename))
    await asyncio.gather(*tasks)

async def download_configuration():
    print(f"--- [{UI}.py] Downloading configuration files and extensions ---")
    ## FILES
    url_cfg = f"https://raw.githubusercontent.com/{FORK_REPO}/{BRANCH}/__configs__"
    configs_to_download = [ # Renamed to avoid conflict
        # settings (Forge typically manages its own config.json and ui-config.json on first run)
        # f"{url_cfg}/{UI}/config.json", # Usually generated by Forge
        # f"{url_cfg}/{UI}/ui-config.json", # Usually generated by Forge
        f"{url_cfg}/styles.csv,{WEBUI}", # Common styles might be applicable
        f"{url_cfg}/user.css,{WEBUI}",   # Common user.css might be applicable
        # other | UI (paths might need Forge-specific adjustments)
        f"{url_cfg}/card-no-preview.png,{WEBUI}/html", # Check if Forge uses this path/file
        f"{url_cfg}/notification.mp3,{WEBUI}", # Check if Forge uses this path/file
        # other | tunneling
        f"{url_cfg}/gradio-tunneling.py,{VENV}/lib/python3.10/site-packages/gradio_tunneling,main.py"
    ]
    await download_files(configs_to_download)

    ## REPOS (Extensions)
    # Forge handles many popular extensions internally or has its own versions.
    # The list below is generic from A1111/Classic and needs review for Forge compatibility/necessity.
    extensions_list = [
        ## ANXETY Edits - Review for Forge
        'https://github.com/anxety-solo/webui_timer timer',
        'https://github.com/anxety-solo/anxety-theme', # Theme might conflict with Forge's theme
        'https://github.com/anxety-solo/sd-civitai-browser-plus Civitai-Browser-Plus',

        ## Gutris1 - Review for Forge
        'https://github.com/gutris1/sd-image-viewer Image-Viewer',
        'https://github.com/gutris1/sd-image-info Image-Info',
        'https://github.com/gutris1/sd-hub SD-Hub',

        ## OTHER | ON - Review for Forge
        # 'https://github.com/Bing-su/adetailer', # Forge has its own ADetailer
        # 'https://github.com/Haoming02/sd-forge-couple SD-Couple', # May need Forge specific version or is built-in
        'https://github.com/hako-mikan/sd-webui-regional-prompter Regional-Prompter', # Check compatibility
    ]
    if ENV_NAME == 'Kaggle':
        extensions_list.append('https://github.com/anxety-solo/sd-encrypt-image Encrypt-Image') # Review for Forge

    FORGE_EXTENSIONS_PATH.mkdir(parents=True, exist_ok=True)
    original_cwd = Path.cwd()
    try:
        CD(FORGE_EXTENSIONS_PATH)
        print(f"--- [{UI}.py] Cloning extensions into {FORGE_EXTENSIONS_PATH} ---")
        tasks = []
        for command_str in extensions_list:
            process = await asyncio.create_subprocess_shell(
                f"git clone --depth 1 {command_str}",
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE
            )
            tasks.append(process)

        for i, process in enumerate(tasks):
            stdout, stderr = await process.communicate()
            if process.returncode != 0:
                print(f"Error cloning extension: {extensions_list[i]}. Git stderr: {stderr.decode() if stderr else 'No stderr'}", file=sys.stderr)
            else:
                print(f"Successfully cloned: {extensions_list[i]}")
    finally:
        CD(original_cwd)

def unpack_webui():
    # Forge is typically installed via git clone, not a zip file from HuggingFace.
    # Adjusting this to clone Forge repository.
    forge_repo_url = "https://github.com/lllyasviel/stable-diffusion-webui-forge.git" # Official Forge repo
    
    print(f"--- [{UI}.py] Step 1: Cloning WebUI from {forge_repo_url} into {WEBUI} ---")
    if WEBUI.exists():
        print(f"--- [{UI}.py] Directory {WEBUI} already exists. Assuming Forge is already cloned or attempting to update. ---")
        # Optionally, add logic here to pull latest changes if directory exists
        # For now, skipping clone if directory exists to prevent errors.
        # A more robust approach would be: if exists, cd and git pull, else git clone.
    else:
        try:
            subprocess.run(["git", "clone", forge_repo_url, str(WEBUI)], check=True, capture_output=True, text=True)
            print(f"--- [{UI}.py] Forge cloned successfully into {WEBUI} ---")
        except subprocess.CalledProcessError as e:
            print(f"--- [{UI}.py] ERROR during git clone of Forge ---", file=sys.stderr)
            print(f"Return Code: {e.returncode}", file=sys.stderr)
            print(f"STDOUT: {e.stdout}", file=sys.stderr)
            print(f"STDERR: {e.stderr}", file=sys.stderr)
            sys.exit(f"Critical error during git clone of Forge. Exiting.")
        except FileNotFoundError:
            print(f"--- [{UI}.py] ERROR: git command not found. Please ensure git is installed and in PATH.", file=sys.stderr)
            sys.exit("Critical error: git command not found. Exiting.")

    # After cloning Forge, run its install.py
    install_script = WEBUI / "install.py"
    if install_script.exists():
        print(f"--- [{UI}.py] Step 2: Running Forge's {install_script} ---")
        python_executable = VENV / "bin" / "python"
        if not python_executable.exists():
            python_executable = sys.executable # Fallback

        original_cwd = Path.cwd()
        try:
            CD(WEBUI) # Run install.py from within Forge directory
            # Forge's install.py might take time and produce a lot of output
            process = subprocess.run([str(python_executable), str(install_script)], capture_output=True, text=True, check=False)
            if process.returncode == 0:
                print(f"--- [{UI}.py] Forge {install_script} executed successfully ---")
                if process.stdout: print(f"Forge install STDOUT:\n{process.stdout}")
            else:
                # Some acceptable "errors" or warnings might occur, Forge install can be complex
                print(f"--- [{UI}.py] Forge {install_script} completed with return code {process.returncode} ---", file=sys.stderr if process.returncode !=0 else sys.stdout)
                if process.stdout: print(f"Forge install STDOUT:\n{process.stdout}", file=sys.stderr if process.returncode !=0 else sys.stdout)
                if process.stderr: print(f"Forge install STDERR:\n{process.stderr}", file=sys.stderr)
                # Not exiting here as Forge's install.py might have non-critical "errors" or complete setup partially.
        except Exception as e:
            print(f"--- [{UI}.py] Exception running Forge {install_script}: {e} ---", file=sys.stderr)
        finally:
            CD(original_cwd)
    else:
        print(f"--- [{UI}.py] Forge {install_script} not found. This is unexpected for a fresh clone. ---", file=sys.stderr)


# ======================== MAIN CODE =======================
if __name__ == '__main__':
    print(f"--- AnxLight {UI} UI Script ---")
    
    unpack_webui() # This now clones Forge and runs install.py
    print(f"--- [{UI}.py] Forge installation process finished, proceeding to download configuration (if any) ---")
    # download_configuration function might need significant review for Forge, as it handles extensions differently.
    # For now, calling it as it was, but its effects on Forge need verification.
    asyncio.run(download_configuration())
    print(f"--- [{UI}.py] Script finished ---")