# ~ ReForge.py | by ANXETY ~
# Refactored by SuperAssistant for standard Python execution
# Note: Panchovix/stable-diffusion-webui-reForge development has reportedly stopped.

from Manager import m_download   # Every Download
import json_utils as js          # JSON

from pathlib import Path
import subprocess
import asyncio
import os
import sys # Ensure sys is imported

osENV = os.environ
CD = os.chdir

# Constants
UI = 'ReForge' # Name of the directory for this UI

# (auto-convert env vars to Path)
PATHS = {k: Path(v) for k, v in osENV.items() if k.endswith('_path')}
HOME = PATHS['home_path']
VENV = PATHS['venv_path'] # VENV should be set up by pre_flight_setup.py
SETTINGS_PATH = PATHS['settings_path']

WEBUI = HOME / UI # Installation directory for ReForge
ENV_NAME = js.read(SETTINGS_PATH, 'ENVIRONMENT.env_name')

# Original REPO_URL pointed to a zip, changing to the git repository
REFORGE_GIT_REPO_URL = "https://github.com/Panchovix/stable-diffusion-webui-reForge.git"
# Configs and extensions are from the generic __configs__ path, review for ReForge specifics
FORK_REPO = js.read(SETTINGS_PATH, 'ENVIRONMENT.fork')
BRANCH = js.read(SETTINGS_PATH, 'ENVIRONMENT.branch')
# ReForge, like Forge, would have its own extensions directory.
REFORGE_EXTENSIONS_PATH = WEBUI / 'extensions'

CD(HOME) # Initial CWD


# ==================== WEBUI OPERATIONS ====================

async def _download_file(url, directory, filename):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    file_path = directory / filename

    if file_path.exists():
        try:
            file_path.unlink()
        except OSError as e:
            print(f"Warning: Could not delete existing file {file_path}. Error: {e}", file=sys.stderr)

    process = await asyncio.create_subprocess_shell(
        f"curl -sLo \"{file_path}\" \"{url}\"", # Added quotes
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE
    )
    stdout, stderr = await process.communicate()
    if process.returncode != 0:
        print(f"Error downloading {url} to {file_path}. curl stderr: {stderr.decode() if stderr else 'No stderr'}", file=sys.stderr)

async def download_files(file_list):
    tasks = []
    for file_info in file_list:
        parts = file_info.split(',')
        url = parts[0].strip()
        directory_str = parts[1].strip() if len(parts) > 1 else str(WEBUI)
        filename = parts[2].strip() if len(parts) > 2 else Path(url).name
        tasks.append(_download_file(url, Path(directory_str), filename))
    await asyncio.gather(*tasks)

async def download_configuration():
    print(f"--- [{UI}.py] Downloading configuration files and extensions (review for ReForge compatibility) ---")
    ## FILES
    url_cfg = f"https://raw.githubusercontent.com/{FORK_REPO}/{BRANCH}/__configs__"
    # These configs are generic; ReForge might generate its own or have different paths.
    configs_to_download = [
        # f"{url_cfg}/{UI}/config.json", # Likely generated by ReForge
        # f"{url_cfg}/{UI}/ui-config.json", # Likely generated by ReForge
        f"{url_cfg}/styles.csv,{WEBUI}",
        f"{url_cfg}/user.css,{WEBUI}",
        f"{url_cfg}/card-no-preview.png,{WEBUI}/html", # Check if ReForge uses this
        f"{url_cfg}/notification.mp3,{WEBUI}",      # Check if ReForge uses this
        f"{url_cfg}/gradio-tunneling.py,{VENV}/lib/python3.10/site-packages/gradio_tunneling,main.py"
    ]
    await download_files(configs_to_download)

    ## REPOS (Extensions) - This list is generic and needs careful review for ReForge
    extensions_list = [
        'https://github.com/anxety-solo/webui_timer timer',
        'https://github.com/anxety-solo/anxety-theme',
        'https://github.com/anxety-solo/sd-civitai-browser-plus Civitai-Browser-Plus',
        'https://github.com/gutris1/sd-image-viewer Image-Viewer',
        'https://github.com/gutris1/sd-image-info Image-Info',
        'https://github.com/gutris1/sd-hub SD-Hub',
        # 'https://github.com/Bing-su/adetailer', # ReForge likely has this or similar built-in
        # 'https://github.com/Haoming02/sd-forge-couple SD-Couple', # Check compatibility
        'https://github.com/hako-mikan/sd-webui-regional-prompter Regional-Prompter',
    ]
    if ENV_NAME == 'Kaggle':
        extensions_list.append('https://github.com/anxety-solo/sd-encrypt-image Encrypt-Image')

    REFORGE_EXTENSIONS_PATH.mkdir(parents=True, exist_ok=True)
    original_cwd = Path.cwd()
    try:
        CD(REFORGE_EXTENSIONS_PATH)
        print(f"--- [{UI}.py] Cloning extensions into {REFORGE_EXTENSIONS_PATH} (review for ReForge compatibility) ---")
        tasks = []
        for command_str in extensions_list:
            process = await asyncio.create_subprocess_shell(
                f"git clone --depth 1 {command_str}",
                stdout=subprocess.DEVNULL,
                stderr=subprocess.PIPE
            )
            tasks.append(process)

        for i, process in enumerate(tasks):
            stdout, stderr = await process.communicate()
            if process.returncode != 0:
                print(f"Error cloning extension: {extensions_list[i]}. Git stderr: {stderr.decode() if stderr else 'No stderr'}", file=sys.stderr)
            else:
                print(f"Successfully cloned: {extensions_list[i]}")
    finally:
        CD(original_cwd)

def unpack_webui():
    print(f"--- [{UI}.py] Step 1: Cloning WebUI from {REFORGE_GIT_REPO_URL} into {WEBUI} ---")
    if WEBUI.exists():
        print(f"--- [{UI}.py] Directory {WEBUI} already exists. Assuming ReForge is already cloned. Add pull logic if update desired. ---")
    else:
        try:
            subprocess.run(["git", "clone", REFORGE_GIT_REPO_URL, str(WEBUI)], check=True, capture_output=True, text=True)
            print(f"--- [{UI}.py] ReForge cloned successfully into {WEBUI} ---")
            # Checkout main branch after cloning
            subprocess.run(["git", "checkout", "main"], cwd=str(WEBUI), check=True, capture_output=True, text=True)
            print(f"--- [{UI}.py] Checked out main branch in {WEBUI} ---")
        except subprocess.CalledProcessError as e:
            print(f"--- [{UI}.py] ERROR during git operation for ReForge ---", file=sys.stderr)
            print(f"Return Code: {e.returncode}", file=sys.stderr)
            print(f"STDOUT: {e.stdout}", file=sys.stderr)
            print(f"STDERR: {e.stderr}", file=sys.stderr)
            sys.exit(f"Critical error during git clone/checkout of ReForge. Exiting.")
        except FileNotFoundError:
            print(f"--- [{UI}.py] ERROR: git command not found. Please ensure git is installed and in PATH.", file=sys.stderr)
            sys.exit("Critical error: git command not found for ReForge. Exiting.")
    
    # ReForge installation is typically completed by running webui-user.sh or webui.py.
    # pre_flight_setup.py will handle VENV activation.
    # Actual dependency installation for ReForge happens on its first proper launch sequence.
    # No explicit 'install.py' is standard for ReForge like it is for lllyasviel/forge.
    # The main setup here is cloning the repository.
    print(f"--- [{UI}.py] ReForge repository cloned. Further setup (dependencies) handled by its first launch. ---")


# ======================== MAIN CODE =======================
if __name__ == '__main__':
    print(f"--- AnxLight {UI} UI Script (Note: {UI} development by Panchovix reportedly stopped) ---")
    
    unpack_webui() # Clones ReForge
    print(f"--- [{UI}.py] ReForge repository clone process finished. ---")
    # Configuration and extension downloads are generic and might need specific adjustments for ReForge.
    asyncio.run(download_configuration())
    print(f"--- [{UI}.py] Script finished ---")